// Reads assets/art/**/*.svg (designer originals, with C2PA metadata) and writes components/art/<group>.ts:
// one named string const per SVG, metadata stripped, ids prefixed (inline SVGs share one document), review fixes applied.
// Inline (never <img>) so fonts of the page apply to <text>. Run: node scripts/build-art.mjs
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const SRC = "assets/art", OUT = "components/art";
mkdirSync(OUT, { recursive: true });

// DESIGN_REVIEW findings 2, 3, 9
const patches = {
  "ill-step-offer": (s) => s.replaceAll("M196 14H284V40H196Z", "M172 14H308V40H172Z"),
  "mascot-apologetic": (s) => s.replace("M61 74L72 78", "M61 78L72 74").replace("M99 74L88 78", "M99 78L88 74"),
  "dia-architecture": (s) => s.replace("auto-repay per sale → close", "auto-repay per sale, then close"),
};

const strip = (s) => s.replace(/<metadata>[\s\S]*?<\/metadata>/g, "").replace(/\sxmlns:c2pa="[^"]*"/g, "");
const camel = (n) => n.replace(/^(icon|logo|ill|badge|dia)-/, (m) => m).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

for (const group of readdirSync(SRC)) {
  let ts = "// GENERATED by scripts/build-art.mjs. Do not edit.\n";
  for (const f of readdirSync(join(SRC, group)).filter((x) => x.endsWith(".svg"))) {
    const name = f.replace(".svg", "");
    let s = readFileSync(join(SRC, group, f), "utf8");
    s = s.replace(/<metadata>[\s\S]*?<\/metadata>/g, "").replace(/\sxmlns:c2pa="[^"]*"/g, "");
    s = (patches[name]?.(s)) ?? s;
    const p = name.replace(/[^a-z0-9]/gi, "");
    s = s.replace(/\bid="([^"]+)"/g, `id="${p}-$1"`).replace(/url\(#([^)]+)\)/g, `url(#${p}-$1)`).replace(/(href)="#([^"]+)"/g, `$1="#${p}-$2"`);
    s = s.replace(/<svg /, '<svg aria-hidden="true" focusable="false" ').replace(/\swidth="[^"]*"/, "").replace(/\sheight="[^"]*"/, "");
    ts += `export const ${JSON.stringify(camel(name)).replace(/"/g, "")} = ${JSON.stringify(s.trim())};\n`;
  }
  writeFileSync(join(OUT, group + ".ts"), ts);
}
// motifs are also used as CSS backgrounds (awning edge, nota edge, kawung): plain stripped files
mkdirSync("public/art/motif", { recursive: true });
for (const f of readdirSync(join(SRC, "motif")).filter((x) => x.endsWith(".svg")))
  writeFileSync(join("public/art/motif", f), strip(readFileSync(join(SRC, "motif", f), "utf8")));
console.log("art built");
